name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Agregar las direcciones IP de las instancias EC2
          ssh-keyscan -H 3.89.180.191 >> ~/.ssh/known_hosts
          ssh-keyscan -H 23.22.169.220 >> ~/.ssh/known_hosts
            ssh-keyscan -H 52.90.34.60 >> ~/.ssh/known_hosts

      # Paso 3: Desplegar los archivos en la primera instancia EC2
      - name: Deploy to Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.89.180.191 << 'EOF'
            cd /home/ec2-user/HTML || git clone https://github.com/mayjade002/HTML.git
            cd HTML
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF

      # Paso 4: Desplegar los archivos en la segunda instancia EC2
      - name: Deploy to Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@23.22.169.220 << 'EOF'
            cd /home/ec2-user/HTML || git clone https://github.com/mayjade002/HTML.git
            cd HTML
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF
       # Paso 4: Desplegar los archivos en la segunda instancia EC2
      - name: Deploy to Instance 3
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.90.34.60 << 'EOF'
            cd /home/ec2-user/HTML || git clone https://github.com/mayjade002/HTML.git
            cd HTML
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF
       # Paso 4: Desplegar los archivos en la segunda instancia EC2
      - name: Deploy to Instance 4
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.175.106.1 << 'EOF'
            cd /home/ec2-user/HTML || git clone https://github.com/mayjade002/HTML.git
            cd HTML
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF
          
